version: '3.8'

services:
  app:
    stdin_open: true
    tty: true
    networks:
      - default

  nginx:
    ports:
      - "8019:80"

  redis:
    image: redis:latest
    container_name: cash_flow_prediction_backend_redis
    ports:
      - "6380:6379"

networks:
  default:
      name: cash_flow_prediction_network
      driver: bridge
