version: '3.8'

services:
  app:
    stdin_open: true
    tty: true
    networks:
      - default

  nginx:
    ports:
      - "8033:80"

networks:
  default:
      name: cash_flow_prediction_network
      driver: bridge
