version: '3.8'

services:

  app:
    stdin_open: true
    tty: true
    networks:
      - default
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: cash_flow_prediction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    networks:
      - default
    ports:
      - "5437:5432"


  redis:
    image: redis:latest
    container_name: cash_flow_prediction_backend_redis
    ports:
      - "6380:6379"


  nginx:
    ports:
      - "8008:80"

volumes:
  postgres_data: