version: '3.8'

services:

  app:
    stdin_open: true
    tty: true
    networks:
      - default

  db:
    image: postgres:latest
    container_name: cash_flow_prediction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    networks:
      - default
    ports:
      - "5438:5432"

  nginx:
    ports:
      - "8000:80"

volumes:
  postgres_data: